### PR TITLE
add unit tests to rhtap

### PR DESCRIPTION
**Pull request by JasonPowr**
This pr adds unit testing to rhtap for fulcio. I've created my own version of fulcio in rhtap in my own workspace and have tested the changes.

## Comments
I only went with that image as its the same used in the Docker files, if it needs to be changed let me know 👍
I believe fulcio can be removed off of open shift release now

### CODE REVIEW

**Comment by JasonPowr** [comment]
If you can access the links you can see them passing, you can also view the logs to confirm

1. https://console.redhat.com/preview/application-pipeline/workspaces/securesign/applications/fulcio/pipelineruns/fulcio-on-pull-request-9pqxx

**Comment by lance** [comment]
@JasonPowr this PR needs to be rebased, can you please take a look?

**Comment by JasonPowr** [comment]
> @JasonPowr this PR needs to be rebased, can you please take a look?

Apologies I forgot this pr was still open, This pr is out of date for the new workspace, ill resolve my changes and basically remove them as you have commits here, ill follow up with a pr for the new workspace for unit tests :)

**Comment by JasonPowr** [comment]
closing this instead, as the only changes are to the patch file thats not needed anymore

**Pull request closed without merging**
